# Generated by Django 5.0.3 on 2024-03-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_delete_product_for_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('microcategory_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'baseline_matrix_1',
                'managed': False,
            },
        ),
    ]
